packages:
  - .

overrides:
  qs: 6.16.0
  tailwindcss>nanoid: 3.3.7
  lodash: 4.18.1
  lodash-es: 4.18.1

patchedDependencies:
  wouter@3.7.1: patches/wouter@3.7.1.patch

onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
