/** Fireside Editorial design: a staggered English Journal index for calm discovery and deliberate conversion. */
import { JournalChrome } from "@/components/JournalChrome";
import { SoundPawMotif } from "@/components/SoundPawMotif";
import { Button } from "@/components/ui/button";
import { journalArticles, journalCategories } from "@/data/journal";
import { ArrowRight, BookOpen, Headphones, Search } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";

const tones: Record<string, string> = { peach: "bg-[#f1dfcf]", moss: "bg-[#dce5d7]", sage: "bg-[#d8e0dc]", ink: "bg-[#302d27] text-[#f5f0e8]" };

export default function Journal() {
  const [category, setCategory] = useState<(typeof journalCategories)[number]>("All");
  const [query, setQuery] = useState("");
  const visibleArticles = useMemo(() => journalArticles.filter((article) => (category === "All" || article.category === category) && `${article.title} ${article.dek}`.toLowerCase().includes(query.toLowerCase())), [category, query]);
  const featured = journalArticles[0];
  return <JournalChrome><main><section className="relative overflow-hidden bg-[#e9e3d6] py-20 sm:py-28"><div className="absolute -left-28 top-8 size-80 rounded-full border border-[#75836D]/25" /><div className="container relative grid gap-10 lg:grid-cols-[1.1fr_.9fr]"><div><p className="eyebrow"><BookOpen className="size-3" />The Journal</p><h1 className="mt-5 font-display text-6xl leading-[.92] tracking-[-.06em] sm:text-8xl">Notes for the<br /><em className="font-normal text-[#75836D]">life you share.</em></h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#625a4f]">Practical gentleness for everyday behavior, small rituals for calmer evenings, and a place to meet grief without rushing it.</p><SoundPawMotif className="mt-9 w-40 text-[#75836D]" /></div><aside className="rounded-[1.8rem] border border-[#d3c7b6] bg-[#fdfaf3]/75 p-7 shadow-[0_18px_45px_rgba(86,67,39,.08)]"><p className="text-[.64rem] font-bold uppercase tracking-[.18em] text-[#75836D]">Start here</p><h2 className="mt-4 font-display text-4xl leading-tight tracking-[-.05em]">A library with room to breathe.</h2><p className="mt-4 text-sm leading-6 text-[#665e53]">Each note links to a listening ritual, a gentle next step, and—where it is genuinely useful—one related digital tool.</p><a href="#all-notes" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-[#5e6d57]">Browse the notes <ArrowRight className="size-4" /></a></aside></div></section>
    <section id="all-notes" className="py-20"><div className="container"><div className="flex flex-col gap-6 border-b border-[#d9d0c0] pb-8 lg:flex-row lg:items-end lg:justify-between dark:border-white/10"><div><p className="eyebrow"><Headphones className="size-3" />{visibleArticles.length} calm reads</p><h2 className="mt-3 font-display text-5xl tracking-[-.05em]">Find the note you need.</h2></div><label className="relative block w-full max-w-sm"><Search className="absolute left-4 top-1/2 size-4 -translate-y-1/2 text-[#75836D]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search the journal" className="w-full rounded-full border border-[#cfc5b4] bg-white py-3 pl-10 pr-4 text-sm outline-none transition focus:border-[#75836D] focus:ring-2 focus:ring-[#75836D]/20 dark:border-white/15 dark:bg-white/5" /></label></div><div className="mt-6 flex flex-wrap gap-2">{journalCategories.map((item) => <button key={item} onClick={() => setCategory(item)} className={`rounded-full px-4 py-2 text-xs font-bold transition ${category === item ? "bg-[#75836D] text-white" : "bg-[#f0ece3] text-[#675e52] hover:bg-[#dce5d7] dark:bg-white/5 dark:text-[#d5cfc4]"}`}>{item}</button>)}</div>
      {category === "All" && !query && <Link href={`/journal/${featured.slug}`} className="group mt-12 grid overflow-hidden rounded-[2rem] bg-[#302d27] text-[#f5f0e8] md:grid-cols-[.8fr_1.2fr]"><div className="relative min-h-72 bg-[#3d453a] p-8"><SoundPawMotif className="absolute bottom-8 left-8 w-40 text-[#b7c7ae]/70" /><p className="relative text-[.65rem] font-bold uppercase tracking-[.18em] text-[#b7c7ae]">Editor’s starting point</p></div><div className="p-8 sm:p-12"><p className="text-[.65rem] font-bold uppercase tracking-[.18em] text-[#e5b17c]">{featured.category} · {featured.readingTime}</p><h3 className="mt-5 font-display text-5xl leading-[.95] tracking-[-.06em]">{featured.title}</h3><p className="mt-5 max-w-xl leading-7 text-[#d3cdbf]">{featured.dek}</p><span className="mt-8 inline-flex items-center gap-2 text-sm font-bold text-[#e5b17c]">Read the note <ArrowRight className="size-4 transition-transform group-hover:translate-x-1" /></span></div></Link>}
      <div className="mt-10 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{visibleArticles.map((article, index) => <Link href={`/journal/${article.slug}`} key={article.slug} className={`group rounded-[1.65rem] border border-[#ded5c7] bg-white p-6 shadow-[0_12px_30px_rgba(71,57,38,.04)] transition hover:-translate-y-1 hover:shadow-xl dark:border-white/10 dark:bg-[#242b24] ${index % 3 === 1 ? "xl:translate-y-8" : ""}`}><div className={`${tones[article.accent]} relative h-36 overflow-hidden rounded-[1.15rem] p-4`}><span className="relative rounded-full bg-white/40 px-2 py-1 text-[.58rem] font-bold uppercase tracking-[.14em] text-[#655d53]">{article.category}</span><SoundPawMotif className="absolute bottom-2 right-2 w-28 text-[#75836D]/55" /></div><p className="mt-6 text-[.63rem] font-bold uppercase tracking-[.16em] text-[#75836D]">{article.label} · {article.readingTime}</p><h3 className="mt-3 font-display text-3xl leading-tight tracking-[-.045em]">{article.title}</h3><p className="mt-3 min-h-20 text-sm leading-6 text-[#675e52] dark:text-[#cfc8bc]">{article.dek}</p><span className="mt-5 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[.15em] text-[#5e6d57]">Read note <ArrowRight className="size-4" /></span></Link>)}</div>{visibleArticles.length === 0 && <div className="mt-12 rounded-[1.5rem] border border-dashed border-[#b9ae9d] p-10 text-center"><p className="font-display text-3xl">Nothing matched that search.</p><Button variant="outline" onClick={() => { setQuery(""); setCategory("All"); }} className="mt-5 rounded-full">Show all notes</Button></div>}</div></section></main></JournalChrome>;
}
