import { JournalChrome } from "@/components/JournalChrome";
import { ArrowRight, BookOpen, Heart, Headphones, Home, Leaf, MessageCircle } from "lucide-react";
import { Link } from "wouter";
import { useEffect } from "react";
import { setPageMeta } from "@/lib/seo";

const paths = [
  { icon: Heart, title: "I’m in the first days", text: "A gentle place to begin when ordinary decisions feel unusually heavy.", href: "/journal/how-to-cope-with-the-loss-of-a-pet", action: "Read the first guide", tone: "bg-[#f1dfcf] text-[#644b3a]" },
  { icon: Home, title: "I want to make a memorial", text: "Small, private ways to gather photographs, objects, words, and rituals at home.", href: "/journal/how-to-create-a-pet-memorial-at-home", action: "Create a quiet memorial", tone: "bg-[#dce5d7] text-[#384136]" },
  { icon: MessageCircle, title: "I’m supporting someone", text: "Thoughtful words for a grieving friend, partner, child, or family member.", href: "/journal/what-to-say-to-someone-who-lost-a-pet", action: "Find kind words", tone: "bg-[#d8e0dc] text-[#30413d]" },
  { icon: Headphones, title: "I need a quiet moment", text: "Listen to Rainbow Bridge and let a soft soundscape accompany the next few minutes.", href: "/#listen", action: "Open the listening room", tone: "bg-[#302d27] text-[#f5f0e8]" },
];

export default function PetLossSupport() {
  useEffect(() => { setPageMeta({ title: "Pet Loss Support | Unsent Melodies", description: "A gentle pet loss support hub with practical guides, memorial ideas, quiet stories, and calming music for grieving pet people.", path: "/pet-loss-support" }); }, []);
  return <JournalChrome><main>
    <section className="relative overflow-hidden bg-[#e9e3d6] py-20 dark:bg-[#202620] sm:py-28"><div className="absolute -right-24 top-10 size-96 rounded-full border border-[#75836D]/25" /><div className="container relative max-w-5xl"><Link href="/start-here" className="text-xs font-bold uppercase tracking-[.16em] text-[#5e6d57] hover:underline">← Start here</Link><p className="eyebrow mt-12"><Leaf className="size-3" />Pet loss support</p><h1 className="mt-5 max-w-4xl font-display text-6xl leading-[.92] tracking-[-.06em] sm:text-8xl">You do not have to<br /><em className="font-normal text-[#75836D]">find every answer today.</em></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#625a4f] dark:text-[#cfc8bc]">A calm collection of practical guidance, remembrance ideas, quiet stories, and music for the days when a beloved pet is missing.</p></div></section>
    <section className="container max-w-5xl py-16 sm:py-20"><div className="grid gap-5 sm:grid-cols-2">{paths.map(({ icon: Icon, title, text, href, action, tone }) => <Link key={title} href={href} className={`group rounded-[1.7rem] p-7 transition duration-200 hover:-translate-y-1 hover:shadow-xl ${tone}`}><Icon className="size-6 opacity-80" /><h2 className="mt-10 font-display text-3xl leading-tight tracking-[-.04em]">{title}</h2><p className="mt-4 max-w-sm text-sm leading-6 opacity-85">{text}</p><span className="mt-7 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[.14em]">{action}<ArrowRight className="size-4 transition-transform group-hover:translate-x-1" /></span></Link>)}</div>
      <div className="mt-14 grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><div className="rounded-[1.7rem] border border-[#ded5c7] bg-[#f5efe4] p-7 dark:border-white/10 dark:bg-white/5"><BookOpen className="size-6 text-[#75836D]" /><h2 className="mt-7 font-display text-3xl tracking-[-.04em]">A few more gentle guides</h2><div className="mt-5 grid gap-3 sm:grid-cols-2"><Link href="/journal/how-to-explain-pet-loss-to-a-child" className="rounded-xl bg-white/60 p-4 text-sm font-semibold hover:bg-white dark:bg-white/5 dark:hover:bg-white/10">Explain pet loss to a child <ArrowRight className="ml-2 inline size-4" /></Link><Link href="/journal/how-to-help-a-grieving-pet-after-another-pet-dies" className="rounded-xl bg-white/60 p-4 text-sm font-semibold hover:bg-white dark:bg-white/5 dark:hover:bg-white/10">Help another pet grieve <ArrowRight className="ml-2 inline size-4" /></Link><Link href="/journal/how-to-remember-a-pet-on-their-birthday" className="rounded-xl bg-white/60 p-4 text-sm font-semibold hover:bg-white dark:bg-white/5 dark:hover:bg-white/10">Remember them on a birthday <ArrowRight className="ml-2 inline size-4" /></Link><Link href="/journal/how-to-make-a-memory-box-for-your-pet" className="rounded-xl bg-white/60 p-4 text-sm font-semibold hover:bg-white dark:bg-white/5 dark:hover:bg-white/10">Make a memory box <ArrowRight className="ml-2 inline size-4" /></Link></div></div><aside className="rounded-[1.7rem] bg-[#75836D] p-7 text-white"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#dce5d7]">A practical companion</p><h2 className="mt-6 font-display text-4xl leading-tight tracking-[-.04em]">After: Pet Loss Support Checklist</h2><p className="mt-4 text-sm leading-6 text-[#e5eddf]">A gentle checklist for the small decisions that follow pet loss—home, belongings, records, family, other pets, and caring for yourself.</p><Link href="/shop" className="mt-7 inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 text-xs font-bold uppercase tracking-[.13em] text-[#506049]">Explore the checklist <ArrowRight className="size-4" /></Link></aside></div>
      <div className="mt-12 rounded-[1.7rem] border border-[#ded5c7] p-7 dark:border-white/10"><p className="text-sm leading-7 text-[#665e53] dark:text-[#cfc8bc]"><strong className="font-display text-2xl text-[#40382f] dark:text-[#f5f0e8]">Take only what helps.</strong><br />This space offers company and general information. If grief feels unsafe or is disrupting daily life, consider contacting a mental-health professional or a pet-loss support service. For health or behavior concerns involving another animal, speak with a qualified veterinarian.</p></div>
    </section>
  </main></JournalChrome>;
}
